# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://qixingjun.tech
date_format: "ordinal"
title: 齐小白
subtitle: "Keep it Simple and Stupid"
description: "齐行君[齐小白]的个人博客"
keywords: 齐行君, 齐小白, QiXingjun, Xingjun Qi
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/QiXingjun/QiXingjun.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Qi Xingjun
organization: Tencent
organization_url: http://www.tencent.com
location: ShangHai, China
email: 18862141550@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类


  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: QiXingjun
douban_username: QiXingjun
facebook_username: QiXingjun
weibo_username: QiXingjun
zhihu_username: QiXingjun
twitter_username: QiXingjun

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
duoshuo_username: qixiaobai
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]


deploy:
  type: git
  repo: 
    github: https://github.com/QiXingjun/QiXingjun.github.io.git
    coding: git@git.coding.net:henryqi/henryqi.git
  branch: master
  message: Keep it Simple and Stupid
  
# Valine comment https://valine.js.org
valine:
  enable: true
  appid: qrKGlS9e7o381tucnCJjSeFd-gzGzoHsz # your leancloud appid
  appkey: ntGifsBf4svqR9FlWKOL1Y0F # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: Just go go # comment box placeholder

